const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./src/data/medicamento.json', 'utf8'));

const INTERACOES = {

'ciclobenzaprina-5mg-10mg': [
  { com: ['álcool','alcool'], nivel: 'alto', titulo: 'Ciclobenzaprina + Álcool', efeito: 'Potencialização intensa da depressão do sistema nervoso central — sedação grave, comprometimento dos reflexos, tontura extrema e risco elevado de acidentes e quedas.', conduta: '❌ Contraindicado. Não consumir álcool durante o tratamento. Risco real de acidentes domésticos, quedas e acidentes de trânsito.' },
  { com: ['diazepam','clonazepam','alprazolam','lorazepam','bromazepam','midazolam'], nivel: 'alto', titulo: 'Ciclobenzaprina + Benzodiazepínico', efeito: 'Soma de efeitos depressores do SNC — sedação excessiva, comprometimento psicomotor grave, confusão mental e risco de depressão respiratória, especialmente em idosos.', conduta: '❌ Evitar a combinação. Se necessário, usar a menor dose possível e nunca dirigir. Risco elevado de queda em idosos.' },
  { com: ['tramadol','codeína','codeina','morfina'], nivel: 'alto', titulo: 'Ciclobenzaprina + Opioide', efeito: 'Potencialização da depressão do SNC com risco de sedação profunda, confusão mental e depressão respiratória.', conduta: '❌ Evitar. Se prescrito, usar doses mínimas e monitorar respiração e nível de consciência.' },
  { com: ['rasagilina','selegilina','tranilcipromina','fenelzina','isocarboxazida'], nivel: 'alto', titulo: 'Ciclobenzaprina + IMAO', efeito: 'Ciclobenzaprina tem estrutura similar aos tricíclicos — combinação com IMAO causa crise hipertensiva grave, hipertermia, convulsões e risco de morte.', conduta: '❌ Contraindicado. Aguardar 14 dias após suspender o IMAO antes de iniciar ciclobenzaprina.' },
  { com: ['fluoxetina','sertralina','escitalopram','paroxetina','venlafaxina','duloxetina'], nivel: 'moderado', titulo: 'Ciclobenzaprina + Antidepressivo (ISRS/IRSN)', efeito: 'Risco de síndrome serotoninérgica — agitação, tremores, sudorese e taquicardia. Ciclobenzaprina também tem atividade serotoninérgica.', conduta: '⚠️ Usar com cautela. Monitorar sintomas neurológicos nas primeiras semanas. Comunicar ao médico se surgir agitação, tremor ou confusão.' },
  { com: ['zolpidem','zopiclona'], nivel: 'moderado', titulo: 'Ciclobenzaprina + Hipnótico', efeito: 'Soma de efeitos sedativos — sonolência excessiva, confusão ao acordar e risco de queda noturna.', conduta: '⚠️ Evitar tomar no mesmo horário. Não dirigir no dia seguinte. Risco elevado em idosos.' },
  { com: ['difenidramina','prometazina','dexclorfeniramina'], nivel: 'moderado', titulo: 'Ciclobenzaprina + Anti-histamínico Sedativo', efeito: 'Efeitos anticolinérgicos somados — boca seca intensa, retenção urinária, constipação, confusão mental e sedação. Muito perigoso em idosos.', conduta: '⚠️ Evitar a combinação. Preferir anti-histamínicos não sedativos (cetirizina, loratadina) se necessário.' }
],

'cetirizina-10mg-e-xarope': [
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Cetirizina + Álcool', efeito: 'Apesar de ser anti-histamínico de segunda geração (menos sedativo), o álcool pode potencializar a sonolência em pessoas mais sensíveis — risco de comprometimento dos reflexos.', conduta: '⚠️ Evitar álcool durante o uso. Atenção ao dirigir ou operar máquinas, especialmente nas primeiras doses.' },
  { com: ['diazepam','clonazepam','alprazolam','lorazepam','bromazepam'], nivel: 'moderado', titulo: 'Cetirizina + Benzodiazepínico', efeito: 'Potencialização da sedação do SNC. Embora a cetirizina cause menos sonolência que anti-histamínicos de 1ª geração, a combinação com benzodiazepínico soma efeitos sedativos.', conduta: '⚠️ Usar com cautela. Preferir tomar à noite. Não dirigir ou operar máquinas pesadas.' },
  { com: ['zolpidem','zopiclona'], nivel: 'moderado', titulo: 'Cetirizina + Hipnótico', efeito: 'Soma de sedação — risco de sonolência excessiva e comprometimento cognitivo no dia seguinte.', conduta: '⚠️ Tomar cetirizina preferencialmente de manhã se usar hipnótico à noite. Monitorar sonolência excessiva.' },
  { com: ['difenidramina','prometazina','dexclorfeniramina','clorfeniramina'], nivel: 'moderado', titulo: 'Duplicação — Dois Anti-histamínicos', efeito: 'Dois anti-histamínicos ao mesmo tempo somam efeitos sem aumentar benefício — risco de sedação excessiva, boca seca, retenção urinária e confusão mental.', conduta: '⚠️ Evitar usar dois anti-histamínicos simultaneamente. Escolher apenas um conforme orientação médica ou farmacêutica.' },
  { tipo: 'duplicacao', classe: 'Anti-histamínico', nivel: 'moderado', titulo: '🔄 Duplicação Terapêutica — Dois Anti-histamínicos', efeito: 'Usar cetirizina junto com loratadina, desloratadina ou outro anti-histamínico não aumenta o efeito antialérgico, mas soma efeitos adversos — sedação, boca seca e tontura.', conduta: '⚠️ Usar apenas um anti-histamínico por vez. Trocar, não acumular.' }
],

'loratadina-10mg-xarope': [
  { com: ['álcool','alcool'], nivel: 'baixo', titulo: 'Loratadina + Álcool', efeito: 'Loratadina praticamente não causa sedação — a interação com álcool é mínima em doses habituais. Pessoas muito sensíveis podem sentir leve tontura.', conduta: '✅ Risco geralmente baixo. Mesmo assim, evite álcool excessivo durante qualquer tratamento.' },
  { com: ['ketoconazol','itraconazol','fluconazol'], nivel: 'moderado', titulo: 'Loratadina + Antifúngico Azólico', efeito: 'Antifúngicos azólicos inibem o CYP3A4 e CYP2D6, reduzindo o metabolismo da loratadina — podem elevar seus níveis séricos, aumentando risco de efeitos adversos (palpitações, tontura).', conduta: '⚠️ Usar com cautela. O risco é baixo em doses padrão, mas comunicar ao médico ou farmacêutico sobre o uso concomitante.' },
  { com: ['claritromicina','eritromicina'], nivel: 'moderado', titulo: 'Loratadina + Macrolídeo', efeito: 'Claritromicina e eritromicina inibem CYP3A4 — elevam os níveis de loratadina moderadamente, podendo aumentar efeitos adversos como palpitações.', conduta: '⚠️ Monitorar palpitações ou tontura. Comunicar ao médico se surgirem sintomas cardíacos.' },
  { com: ['difenidramina','prometazina','dexclorfeniramina','clorfeniramina','cetirizina','desloratadina'], nivel: 'moderado', titulo: 'Loratadina + Outro Anti-histamínico', efeito: 'Usar dois anti-histamínicos ao mesmo tempo não aumenta o efeito antialérgico — apenas soma efeitos adversos sem benefício adicional.', conduta: '⚠️ Usar apenas um anti-histamínico por vez. Trocar, não combinar.' },
  { tipo: 'duplicacao', classe: 'Anti-histamínico', nivel: 'moderado', titulo: '🔄 Duplicação Terapêutica — Dois Anti-histamínicos', efeito: 'Combinar loratadina com cetirizina, desloratadina ou outro anti-histamínico não traz benefício adicional e aumenta o risco de efeitos adversos.', conduta: '⚠️ Usar apenas um anti-histamínico por vez, conforme orientação médica ou farmacêutica.' }
],

'desloratadina-5mg-xarope': [
  { com: ['álcool','alcool'], nivel: 'baixo', titulo: 'Desloratadina + Álcool', efeito: 'Desloratadina é um dos anti-histamínicos com menor potencial sedativo — interação com álcool é mínima em doses habituais.', conduta: '✅ Risco geralmente baixo. Evite álcool excessivo durante qualquer tratamento.' },
  { com: ['ketoconazol','itraconazol','eritromicina','claritromicina'], nivel: 'baixo', titulo: 'Desloratadina + Inibidor de CYP3A4', efeito: 'Inibidores do CYP3A4 podem elevar levemente os níveis de desloratadina, mas estudos clínicos mostram que essa elevação não causou alterações eletrocardiográficas ou efeitos adversos relevantes.', conduta: '✅ Risco clínico mínimo nas doses habituais. Informar ao médico sobre todos os medicamentos em uso.' },
  { com: ['difenidramina','prometazina','dexclorfeniramina','clorfeniramina','cetirizina','loratadina'], nivel: 'moderado', titulo: 'Desloratadina + Outro Anti-histamínico', efeito: 'Usar dois anti-histamínicos simultaneamente não aumenta o alívio alérgico — apenas soma efeitos indesejados.', conduta: '⚠️ Usar apenas um anti-histamínico por vez. Trocar, não acumular.' },
  { tipo: 'duplicacao', classe: 'Anti-histamínico', nivel: 'moderado', titulo: '🔄 Duplicação Terapêutica — Dois Anti-histamínicos', efeito: 'Combinar desloratadina com outros anti-histamínicos não traz benefício adicional e pode causar efeitos adversos desnecessários.', conduta: '⚠️ Usar apenas um anti-histamínico por vez, conforme orientação médica ou farmacêutica.' }
],

'amoxicilina-250mg-500mg-suspensao': [
  { com: ['warfarina','varfarina','acenocumarol'], nivel: 'moderado', titulo: 'Amoxicilina + Anticoagulante Oral', efeito: 'Amoxicilina altera a flora intestinal produtora de vitamina K — pode potencializar o efeito anticoagulante, elevando o INR e o risco de sangramento. O efeito varia entre pacientes.', conduta: '⚠️ Monitorar INR durante e após o antibiótico. Informar sempre ao médico sobre uso de anticoagulante antes de iniciar qualquer antibiótico.' },
  { com: ['metotrexato'], nivel: 'moderado', titulo: 'Amoxicilina + Metotrexato', efeito: 'Amoxicilina pode reduzir a eliminação renal do metotrexato — eleva seus níveis séricos com risco de toxicidade (mucosite, supressão da medula óssea).', conduta: '⚠️ Comunicar ao reumatologista ou oncologista antes de usar antibiótico. Monitorar sintomas de toxicidade.' },
  { com: ['probenecida'], nivel: 'moderado', titulo: 'Amoxicilina + Probenecida', efeito: 'Probenecida bloqueia a excreção renal da amoxicilina — eleva e prolonga seus níveis séricos.', conduta: '⚠️ A combinação pode ser usada intencionalmente pelo médico para ampliar o efeito. Não ajustar doses por conta própria.' },
  { com: ['etinilestradiol','anticoncepcional','contraceptivo oral'], nivel: 'baixo', titulo: 'Amoxicilina + Anticoncepcional Oral', efeito: 'Evidências atuais indicam que a interação é mínima e improvável de causar falha contraceptiva. Estudos antigos superestimaram esse risco.', conduta: '✅ Não é necessário usar método adicional. Manter o anticoncepcional normalmente. Em caso de dúvida, consultar médico ou farmacêutico.' },
  { com: ['álcool','alcool'], nivel: 'baixo', titulo: 'Amoxicilina + Álcool', efeito: 'Ao contrário do metronidazol, amoxicilina não causa reação grave com álcool. No entanto, álcool pode comprometer o sistema imune e dificultar a recuperação da infecção.', conduta: '✅ Não há interação direta grave. Mesmo assim, evite álcool durante o tratamento de qualquer infecção para favorecer a recuperação.' },
  { com: ['alopurinol'], nivel: 'moderado', titulo: 'Amoxicilina + Alopurinol', efeito: 'Combinação aumenta significativamente o risco de reações cutâneas (erupções na pele) — a incidência de rash chega a 20% com essa associação.', conduta: '⚠️ Monitorar pele durante o tratamento. Comunicar ao médico se surgir vermelhidão, coceira ou manchas.' }
],

'cefalexina-500mg-10g-suspensao': [
  { com: ['warfarina','varfarina','acenocumarol'], nivel: 'moderado', titulo: 'Cefalexina + Anticoagulante Oral', efeito: 'Cefalexina pode alterar a flora intestinal e interfere no metabolismo da warfarina — potencializa o efeito anticoagulante com risco de elevação do INR e sangramento.', conduta: '⚠️ Monitorar INR durante e após o antibiótico. Informar sempre ao médico sobre uso de anticoagulante antes de iniciar qualquer antibiótico.' },
  { com: ['probenecida'], nivel: 'moderado', titulo: 'Cefalexina + Probenecida', efeito: 'Probenecida bloqueia a secreção tubular renal da cefalexina — eleva e prolonga seus níveis séricos, aumentando o risco de efeitos adversos com altas doses.', conduta: '⚠️ Monitorar sinais de toxicidade. A combinação pode ser usada intencionalmente pelo médico.' },
  { com: ['metformina'], nivel: 'baixo', titulo: 'Cefalexina + Metformina', efeito: 'Cefalexina pode competir com a metformina pela secreção tubular renal — leve elevação dos níveis de metformina em alguns pacientes, geralmente sem significado clínico relevante.', conduta: '✅ Monitorar glicemia durante o uso do antibiótico. Risco clínico geralmente mínimo.' },
  { com: ['álcool','alcool'], nivel: 'baixo', titulo: 'Cefalexina + Álcool', efeito: 'Cefalexina não causa reação tipo dissulfiram com álcool (ao contrário do metronidazol). O álcool pode causar náusea junto com o antibiótico e prejudicar a recuperação da infecção.', conduta: '✅ Não há interação direta grave. Evite álcool para favorecer a recuperação.' }
],

'levofloxacina-500mg-750mg-injetavel': [
  { com: ['warfarina','varfarina','acenocumarol'], nivel: 'alto', titulo: 'Levofloxacina + Anticoagulante Oral', efeito: 'Levofloxacina potencializa fortemente o efeito anticoagulante da warfarina — INR pode dobrar em 2–3 dias com risco de hemorragia grave (digestiva, intracraniana).', conduta: '❌ Monitorar INR em 2–3 dias após iniciar o antibiótico. Alertar sobre sinais de sangramento (urina avermelhada, fezes escuras, hematomas). Reduzir dose de warfarina se necessário.' },
  { com: ['amiodarona','sotalol','dronedarona','haloperidol','risperidona','quetiapina'], nivel: 'alto', titulo: 'Levofloxacina + Medicamentos que Prolongam QT', efeito: 'Levofloxacina prolonga o intervalo QT — combinação com outros medicamentos que também prolongam o QT multiplica o risco de arritmia grave (torsades de pointes) e parada cardíaca.', conduta: '❌ Evitar a combinação. Se imprescindível, monitorar ECG. Comunicar cardiologista.' },
  { com: ['insulina','glibenclamida','gliclazida','glimepirida','metformina'], nivel: 'moderado', titulo: 'Levofloxacina + Antidiabético', efeito: 'Fluoroquinolonas podem causar tanto hipoglicemia quanto hiperglicemia — desregulação glicêmica imprevisível em diabéticos.', conduta: '⚠️ Monitorar glicemia com mais frequência durante o tratamento. Ajustar antidiabético conforme orientação médica.' },
  { com: ['antiácido','hidróxido de alumínio','hidróxido de magnésio','carbonato de cálcio','sucralfato'], nivel: 'moderado', titulo: 'Levofloxacina + Antiácido / Ferro / Cálcio', efeito: 'Antiácidos com alumínio, magnésio ou cálcio, além de ferro e zinco, quelam a levofloxacina no intestino — reduzem significativamente sua absorção e eficácia.', conduta: '⚠️ Tomar levofloxacina 2h antes ou 6h depois de antiácidos, ferro ou suplementos de cálcio. Não tomar junto.' },
  { com: ['teofilina'], nivel: 'moderado', titulo: 'Levofloxacina + Teofilina', efeito: 'Levofloxacina pode elevar os níveis séricos de teofilina — risco de toxicidade (náusea, vômito, taquicardia, convulsões).', conduta: '⚠️ Monitorar sinais de toxicidade por teofilina. Pode ser necessário reduzir a dose de teofilina.' },
  { com: ['ibuprofeno','diclofenaco','nimesulida','meloxicam','naproxeno'], nivel: 'moderado', titulo: 'Levofloxacina + AINE', efeito: 'AINEs combinados com fluoroquinolonas aumentam o risco de convulsões — mecanismo relacionado ao antagonismo do GABA no SNC.', conduta: '⚠️ Evitar AINEs durante o tratamento com levofloxacina. Preferir paracetamol ou dipirona para dor e febre.' },
  { com: ['prednisona','prednisolona','dexametasona','betametasona'], nivel: 'moderado', titulo: 'Levofloxacina + Corticoide', efeito: 'Uso simultâneo de fluoroquinolona e corticoide aumenta significativamente o risco de ruptura de tendão (especialmente tendão de Aquiles) — risco maior em idosos e em uso prolongado.', conduta: '⚠️ Interromper imediatamente se sentir dor ou inchaço nos tendões. Comunicar ao médico. Evitar exercícios intensos durante o tratamento.' }
],

'sibutramina-10mg-15mg': [
  { com: ['fluoxetina','sertralina','escitalopram','paroxetina','citalopram','venlafaxina','duloxetina'], nivel: 'alto', titulo: 'Sibutramina + Antidepressivo ISRS/IRSN', efeito: 'Risco grave de síndrome serotoninérgica — agitação intensa, tremores, febre alta, taquicardia, convulsões e risco de morte. Sibutramina é um inibidor da recaptação de serotonina e noradrenalina.', conduta: '❌ Contraindicado. Nunca associar sibutramina com antidepressivos serotoninérgicos. Comunicar TODOS os medicamentos em uso ao médico.' },
  { com: ['rasagilina','selegilina','tranilcipromina','fenelzina','isocarboxazida','linezolida'], nivel: 'alto', titulo: 'Sibutramina + IMAO', efeito: 'Risco extremo de síndrome serotoninérgica grave e crise hipertensiva — potencialmente fatal.', conduta: '❌ Contraindicado. Aguardar 14 dias após suspender qualquer IMAO antes de iniciar sibutramina.' },
  { com: ['tramadol','codeína','triptano','sumatriptana','rizatriptana'], nivel: 'alto', titulo: 'Sibutramina + Tramadol / Triptano', efeito: 'Risco de síndrome serotoninérgica — agitação, tremores, taquicardia e hipertermia.', conduta: '❌ Evitar a combinação. Comunicar ao médico todos os medicamentos em uso.' },
  { com: ['pseudoefedrina','fenilefrina','efedrina'], nivel: 'alto', titulo: 'Sibutramina + Descongestionante (Pseudoefedrina)', efeito: 'Soma de efeitos adrenérgicos — risco de crise hipertensiva grave, taquicardia e eventos cardiovasculares.', conduta: '❌ Evitar descongestionantes nasais ou orais com pseudoefedrina ou fenilefrina durante o uso de sibutramina.' },
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Sibutramina + Álcool', efeito: 'Álcool aumenta o apetite e compromete o controle alimentar — prejudica diretamente o objetivo do tratamento. Além disso, pode potencializar efeitos cardiovasculares.', conduta: '⚠️ Evitar álcool durante o tratamento. Comprometimento do efeito terapêutico e risco cardiovascular aumentado.' },
  { com: ['sinvastatina','atorvastatina','rosuvastatina'], nivel: 'moderado', titulo: 'Sibutramina + Estatina (via CYP3A4)', efeito: 'Sibutramina é metabolizada pelo CYP3A4 — inibidores potentes dessa via podem elevar seus níveis séricos, potencializando efeitos cardiovasculares adversos.', conduta: '⚠️ Monitorar pressão arterial e frequência cardíaca. Ajuste médico pode ser necessário.' }
],

'acenocumarol-1mg-4mg': [
  { com: ['ibuprofeno','diclofenaco','nimesulida','cetoprofeno','meloxicam','naproxeno','aine'], nivel: 'alto', titulo: 'Acenocumarol + Anti-inflamatório (AINE)', efeito: 'AINEs potencializam o efeito anticoagulante e irritam a mucosa gástrica — risco muito elevado de sangramento gastrointestinal grave.', conduta: '❌ Contraindicado. Usar paracetamol ou dipirona para dor e febre. Nunca usar AINE sem autorização médica.' },
  { com: ['aspirina','ácido acetilsalicílico','aas'], nivel: 'alto', titulo: 'Acenocumarol + Aspirina / AAS', efeito: 'Combinação de anticoagulante + antiagregante plaquetário multiplica o risco de sangramento grave — hemorragia digestiva e intracraniana.', conduta: '❌ Evitar salvo indicação médica específica. Uso conjunto só com acompanhamento rigoroso.' },
  { com: ['amiodarona'], nivel: 'alto', titulo: 'Amiodarona + Acenocumarol', efeito: 'Amiodarona inibe o metabolismo do acenocumarol via CYP2C9 — potencializa fortemente o efeito anticoagulante com risco de hemorragia grave.', conduta: '❌ Reduzir dose de acenocumarol em 30–50% ao iniciar amiodarona. Monitorar INR semanalmente nas primeiras semanas.' },
  { com: ['fluconazol','itraconazol','voriconazol'], nivel: 'alto', titulo: 'Acenocumarol + Antifúngico Azólico', efeito: 'Antifúngicos azólicos inibem fortemente o CYP2C9 — elevam muito os níveis de acenocumarol com risco de hemorragia grave.', conduta: '❌ Monitorar INR com muita frequência. Reduzir dose de acenocumarol conforme necessário. Comunicar ao médico.' },
  { com: ['rifampicina'], nivel: 'alto', titulo: 'Rifampicina + Acenocumarol', efeito: 'Rifampicina é indutor potente do CYP2C9 — reduz drasticamente os níveis de acenocumarol com risco de trombose e AVC.', conduta: '❌ Aumentar dose de acenocumarol e monitorar INR com muita frequência durante e após o uso de rifampicina.' },
  { com: ['fluoxetina','sertralina','paroxetina','escitalopram','venlafaxina'], nivel: 'moderado', titulo: 'Acenocumarol + ISRS', efeito: 'ISRS inibem o metabolismo via CYP2C9 e têm efeito antiagregante plaquetário — elevam o INR e o risco de sangramento.', conduta: '⚠️ Monitorar INR ao iniciar ou ajustar dose do antidepressivo.' },
  { com: ['paracetamol'], nivel: 'moderado', titulo: 'Acenocumarol + Paracetamol (dose alta)', efeito: 'Paracetamol em doses acima de 2g/dia pode potencializar o efeito anticoagulante — risco de sangramento inesperado. É o analgésico preferido, mas em doses controladas.', conduta: '⚠️ Usar paracetamol na menor dose eficaz (máx. 2g/dia). Monitorar INR com uso regular.' },
  { com: ['sinvastatina','atorvastatina','rosuvastatina'], nivel: 'moderado', titulo: 'Estatina + Acenocumarol', efeito: 'Algumas estatinas inibem CYP2C9 — podem elevar os níveis de acenocumarol com risco de potencialização do efeito anticoagulante.', conduta: '⚠️ Monitorar INR ao iniciar, trocar ou ajustar dose da estatina.' },
  { com: ['ciprofloxacino','levofloxacino','moxifloxacino'], nivel: 'alto', titulo: 'Fluoroquinolona + Acenocumarol', efeito: 'Fluoroquinolonas potencializam o efeito anticoagulante — INR pode subir rapidamente com risco de hemorragia grave.', conduta: '❌ Monitorar INR em 2–3 dias após iniciar o antibiótico. Alertar o paciente sobre sinais de sangramento.' },
  { com: ['claritromicina','eritromicina','azitromicina'], nivel: 'moderado', titulo: 'Acenocumarol + Macrolídeo', efeito: 'Macrolídeos podem potencializar o efeito anticoagulante do acenocumarol — risco de elevação do INR e sangramento.', conduta: '⚠️ Monitorar INR durante e após o antibiótico.' }
],

'ciclosporina': [
  { com: ['sinvastatina','lovastatina','atorvastatina','rosuvastatina'], nivel: 'alto', titulo: 'Ciclosporina + Estatina', efeito: 'Ciclosporina inibe fortemente o CYP3A4 e transportadores OATP — eleva muito os níveis de estatinas com risco grave de miopatia e rabdomiólise (destruição muscular que pode causar insuficiência renal).', conduta: '❌ Sinvastatina e lovastatina são contraindicadas. Atorvastatina deve ser usada em dose mínima (10mg). Rosuvastatina máx. 5mg. Monitorar CK e função renal regularmente.' },
  { com: ['ibuprofeno','diclofenaco','naproxeno','meloxicam','aine'], nivel: 'alto', titulo: 'Ciclosporina + AINE', efeito: 'AINEs reduzem o fluxo sanguíneo renal e somam nefrotoxicidade com a ciclosporina — risco de lesão renal aguda grave.', conduta: '❌ Evitar AINEs. Usar paracetamol ou dipirona para dor. Monitorar função renal se uso inevitável.' },
  { com: ['claritromicina','eritromicina','azitromicina'], nivel: 'alto', titulo: 'Ciclosporina + Macrolídeo', efeito: 'Macrolídeos inibem CYP3A4 — elevam significativamente os níveis de ciclosporina com risco de nefrotoxicidade, hepatotoxicidade e imunossupressão excessiva.', conduta: '❌ Monitorar nível sérico de ciclosporina ao iniciar antibiótico. Pode ser necessário reduzir a dose de ciclosporina.' },
  { com: ['fluconazol','itraconazol','voriconazol','cetoconazol'], nivel: 'alto', titulo: 'Ciclosporina + Antifúngico Azólico', efeito: 'Antifúngicos azólicos inibem fortemente CYP3A4 — podem dobrar ou triplicar os níveis de ciclosporina com risco de toxicidade grave.', conduta: '❌ Monitorar nível sérico de ciclosporina frequentemente. Reduzir dose conforme necessário. Uso apenas com supervisão especializada.' },
  { com: ['rifampicina'], nivel: 'alto', titulo: 'Rifampicina + Ciclosporina', efeito: 'Rifampicina induz fortemente CYP3A4 — pode reduzir os níveis de ciclosporina em 80–90%, causando rejeição em transplantados.', conduta: '❌ Combinação extremamente perigosa em transplantados. Monitorar nível sérico e ajustar dose drasticamente. Buscar antibiótico alternativo.' },
  { com: ['diltiazem','verapamil'], nivel: 'moderado', titulo: 'Ciclosporina + Diltiazem / Verapamil', efeito: 'Diltiazem e verapamil inibem CYP3A4 — elevam os níveis de ciclosporina com risco de nefrotoxicidade.', conduta: '⚠️ Monitorar nível sérico de ciclosporina e função renal ao iniciar, ajustar ou suspender esses medicamentos.' },
  { com: ['hipericão','erva-de-são-joão','hypericum'], nivel: 'alto', titulo: 'Ciclosporina + Hipericão (Erva-de-São-João)', efeito: 'Hipericão é indutor potente do CYP3A4 — pode reduzir os níveis de ciclosporina em até 50%, causando rejeição de órgão transplantado.', conduta: '❌ Contraindicado em transplantados e em qualquer paciente usando ciclosporina. Nunca usar fitoterápicos sem comunicar ao médico.' },
  { com: ['espironolactona','amilorida'], nivel: 'moderado', titulo: 'Ciclosporina + Diurético Poupador de Potássio', efeito: 'Ciclosporina retém potássio — combinação com diuréticos poupadores de potássio aumenta risco de hipercalemia (potássio alto), que pode causar arritmia grave.', conduta: '⚠️ Monitorar nível de potássio sérico regularmente. Evitar suplementos de potássio sem orientação médica.' },
  { com: ['toronja','suco de grapefruit'], nivel: 'moderado', titulo: 'Ciclosporina + Suco de Toranja (Grapefruit)', efeito: 'Suco de toranja inibe CYP3A4 intestinal — pode elevar os níveis de ciclosporina de forma imprevisível, aumentando risco de toxicidade.', conduta: '⚠️ Evitar toranja e suco de grapefruit durante o tratamento com ciclosporina.' }
],

'baclofen-10mg': [
  { com: ['álcool','alcool'], nivel: 'alto', titulo: 'Baclofen + Álcool', efeito: 'Potencialização intensa da depressão do SNC — sedação grave, comprometimento dos reflexos, tontura extrema e risco de depressão respiratória. Baclofen já causa sonolência considerável isoladamente.', conduta: '❌ Contraindicado. Não consumir álcool durante o tratamento. Risco real de acidentes, quedas e depressão respiratória.' },
  { com: ['diazepam','clonazepam','alprazolam','lorazepam','bromazepam','midazolam'], nivel: 'alto', titulo: 'Baclofen + Benzodiazepínico', efeito: 'Soma de depressores do SNC — sedação profunda, hipotonia muscular excessiva, confusão mental e risco de depressão respiratória, especialmente em idosos.', conduta: '❌ Evitar a combinação. Se necessário, usar a menor dose possível. Nunca dirigir ou operar máquinas.' },
  { com: ['tramadol','codeína','morfina','fentanila'], nivel: 'alto', titulo: 'Baclofen + Opioide', efeito: 'Potencialização da depressão do SNC — sedação grave e risco de depressão respiratória potencialmente fatal.', conduta: '❌ Evitar. Se prescrito, monitorar rigorosamente respiração e nível de consciência.' },
  { com: ['lítio','carbonato de lítio'], nivel: 'moderado', titulo: 'Baclofen + Lítio', efeito: 'Relatos de alucinações e agravamento de sintomas neurológicos com essa combinação. Mecanismo não completamente esclarecido.', conduta: '⚠️ Monitorar sintomas neuropsiquiátricos. Comunicar ao psiquiatra sobre qualquer alteração de comportamento.' },
  { com: ['amitriptilina','nortriptilina','imipramina','clomipramina'], nivel: 'moderado', titulo: 'Baclofen + Antidepressivo Tricíclico', efeito: 'Tricíclicos podem potencializar a hipotonia muscular e a sedação do baclofen. Combinação pode também causar hipotensão.', conduta: '⚠️ Usar com cautela. Monitorar fraqueza muscular excessiva e pressão arterial.' },
  { com: ['captopril','enalapril','lisinopril','losartana','anlodipino','hidroclorotiazida'], nivel: 'moderado', titulo: 'Baclofen + Anti-hipertensivo', efeito: 'Baclofen pode potencializar o efeito hipotensor — risco de hipotensão sintomática, tontura ao levantar e quedas.', conduta: '⚠️ Levantar devagar da cadeira ou cama. Monitorar pressão arterial ao iniciar ou ajustar doses. Risco maior em idosos.' },
  { com: ['zolpidem','zopiclona'], nivel: 'moderado', titulo: 'Baclofen + Hipnótico', efeito: 'Soma de efeitos sedativos e relaxantes musculares — sonolência excessiva, confusão ao acordar e risco de quedas.', conduta: '⚠️ Evitar tomar no mesmo horário. Não dirigir. Risco elevado em idosos.' }
],

'montelucaste-4mg-5mg-10mg': [
  { com: ['fenobarbital','rifampicina','carbamazepina','fenitoína'], nivel: 'moderado', titulo: 'Montelucaste + Indutor Enzimático', efeito: 'Indutores do CYP3A4/CYP2C9 (fenobarbital, rifampicina, carbamazepina) aceleram o metabolismo do montelucaste — podem reduzir seus níveis e eficácia.', conduta: '⚠️ Monitorar controle da asma e rinite. Comunicar ao médico se os sintomas piorarem durante o uso do indutor.' },
  { com: ['fluoxetina','sertralina','escitalopram','paroxetina','venlafaxina'], nivel: 'moderado', titulo: 'Montelucaste + Antidepressivo', efeito: 'A FDA emitiu alerta sobre risco de efeitos neuropsiquiátricos graves com montelucaste (depressão, pensamentos suicidas, alterações de comportamento) — antidepressivos podem mascarar ou interagir com esses efeitos.', conduta: '⚠️ Monitorar alterações de humor, comportamento ou sono ao iniciar montelucaste. Comunicar imediatamente ao médico qualquer alteração psiquiátrica.' },
  { com: ['warfarina','varfarina','acenocumarol'], nivel: 'baixo', titulo: 'Montelucaste + Anticoagulante Oral', efeito: 'Montelucaste pode interferir levemente no metabolismo da warfarina via CYP2C9. O impacto clínico é geralmente mínimo, mas documentado.', conduta: '✅ Risco clínico geralmente baixo. Monitorar INR ao iniciar montelucaste em pacientes anticoagulados.' },
  { com: ['álcool','alcool'], nivel: 'baixo', titulo: 'Montelucaste + Álcool', efeito: 'Não há interação farmacocinética significativa. No entanto, álcool pode piorar sintomas alérgicos e asmáticos — sensação de nariz entupido e broncoespasmo em pessoas sensíveis.', conduta: '✅ Sem interação medicamentosa grave. Evite álcool se tiver histórico de piora alérgica com bebidas.' }
],

'modafinil-100mg-200mg': [
  { com: ['etinilestradiol','anticoncepcional','contraceptivo oral','levonorgestrel'], nivel: 'alto', titulo: 'Modafinil + Anticoncepcional Oral', efeito: 'Modafinil induz CYP3A4 — reduz significativamente os níveis dos contraceptivos hormonais, podendo causar falha contraceptiva e gravidez indesejada.', conduta: '❌ Usar método contraceptivo adicional não hormonal (camisinha) durante o uso de modafinil E por 1 mês após a suspensão. Comunicar ao ginecologista.' },
  { com: ['ciclosporina'], nivel: 'moderado', titulo: 'Modafinil + Ciclosporina', efeito: 'Modafinil induz CYP3A4 — pode reduzir os níveis de ciclosporina em até 50%, causando risco de rejeição em transplantados.', conduta: '❌ Monitorar nível sérico de ciclosporina ao iniciar ou suspender modafinil. Ajuste de dose necessário.' },
  { com: ['warfarina','varfarina'], nivel: 'moderado', titulo: 'Modafinil + Warfarina', efeito: 'Modafinil pode inibir CYP2C9 — eleva os níveis de warfarina com risco de aumento do efeito anticoagulante e sangramento.', conduta: '⚠️ Monitorar INR ao iniciar, ajustar ou suspender modafinil.' },
  { com: ['cafeína'], nivel: 'baixo', titulo: 'Modafinil + Cafeína', efeito: 'Soma de estimulantes do SNC — pode causar nervosismo, ansiedade, palpitações e insônia intensa.', conduta: '⚠️ Reduzir consumo de café e energéticos durante o uso de modafinil. Monitorar frequência cardíaca.' },
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Modafinil + Álcool', efeito: 'Álcool pode contrabalancear o efeito estimulante do modafinil e causar comportamentos de risco (sensação de estar mais sóbrio do que realmente está). Também prejudica o sono, anulando o benefício do modafinil.', conduta: '⚠️ Evitar álcool durante o tratamento. Risco de subestimar o grau de intoxicação.' },
  { com: ['rasagilina','selegilina','tranilcipromina'], nivel: 'moderado', titulo: 'Modafinil + IMAO', efeito: 'Combinação pode potencializar efeitos adrenérgicos — risco de crise hipertensiva e sintomas cardiovasculares.', conduta: '⚠️ Evitar a combinação. Comunicar ao médico todos os medicamentos em uso.' },
  { com: ['fenitoína','carbamazepina'], nivel: 'moderado', titulo: 'Modafinil + Anticonvulsivante (CYP2C19)', efeito: 'Modafinil inibe CYP2C19 — pode elevar os níveis de fenitoína com risco de toxicidade (tontura, diplopia, ataxia).', conduta: '⚠️ Monitorar sinais de toxicidade por fenitoína. Nível sérico pode precisar de ajuste.' }
],

'dronedarona-400mg': [
  { com: ['sinvastatina','lovastatina'], nivel: 'alto', titulo: 'Dronedarona + Sinvastatina / Lovastatina', efeito: 'Dronedarona inibe fortemente CYP3A4 — eleva muito os níveis de sinvastatina e lovastatina com risco grave de miopatia e rabdomiólise (destruição muscular que pode causar insuficiência renal).', conduta: '❌ Sinvastatina acima de 10mg e lovastatina são contraindicadas com dronedarona. Preferir rosuvastatina ou pravastatina (menor interação).' },
  { com: ['digoxina'], nivel: 'alto', titulo: 'Dronedarona + Digoxina', efeito: 'Dronedarona inibe transportadores que eliminam a digoxina — eleva seus níveis em até 2,5x com risco de toxicidade digitálica (náusea, bradicardia grave, arritmia).', conduta: '❌ Reduzir dose de digoxina em 50% ao iniciar dronedarona. Monitorar nível sérico de digoxina e ECG.' },
  { com: ['diltiazem','verapamil'], nivel: 'alto', titulo: 'Dronedarona + Diltiazem / Verapamil', efeito: 'Dronedarona inibe CYP3A4 — eleva os níveis de diltiazem e verapamil. Soma de efeitos cronotrópicos negativos — bradicardia grave e bloqueio atrioventricular.', conduta: '❌ Evitar a combinação. Se necessária, iniciar diltiazem ou verapamil em dose muito baixa com monitorização cardíaca.' },
  { com: ['warfarina','varfarina','acenocumarol'], nivel: 'moderado', titulo: 'Dronedarona + Anticoagulante Oral', efeito: 'Dronedarona pode potencializar o efeito anticoagulante da warfarina — risco de elevação do INR e sangramento.', conduta: '⚠️ Monitorar INR com frequência ao iniciar ou ajustar dronedarona.' },
  { com: ['rivaroxabana','apixabana'], nivel: 'moderado', titulo: 'Dronedarona + NOAC (Rivaroxabana / Apixabana)', efeito: 'Dronedarona inibe CYP3A4 e P-gp — eleva os níveis de rivaroxabana e apixabana com risco de potencialização do efeito anticoagulante e sangramento.', conduta: '⚠️ Monitorar sinais de sangramento. Comunicar ao médico toda associação com anticoagulante.' },
  { com: ['amiodarona','sotalol','haloperidol','quetiapina','levofloxacina'], nivel: 'alto', titulo: 'Dronedarona + Medicamento que Prolonga QT', efeito: 'Dronedarona já prolonga o QT — combinação com outros medicamentos que prolongam o QT multiplica o risco de arritmia grave (torsades de pointes) e parada cardíaca.', conduta: '❌ Evitar a combinação. Monitorar ECG se inevitável. Comunicar cardiologista.' },
  { com: ['rifampicina','carbamazepina','fenitoína','hipericão'], nivel: 'alto', titulo: 'Dronedarona + Indutor do CYP3A4', efeito: 'Indutores potentes do CYP3A4 reduzem os níveis de dronedarona em até 80% — perda do efeito antiarrítmico com risco de recidiva de fibrilação atrial.', conduta: '❌ Contraindicado. Buscar alternativa ao indutor enzimático ou ao antiarrítmico.' },
  { com: ['ketoconazol','itraconazol','voriconazol','claritromicina'], nivel: 'alto', titulo: 'Dronedarona + Inibidor Potente do CYP3A4', efeito: 'Inibidores potentes do CYP3A4 elevam os níveis de dronedarona em mais de 3x — risco de toxicidade cardíaca grave.', conduta: '❌ Contraindicado. Buscar antifúngico ou antibiótico alternativo.' }
],

'sotalol-80mg-160mg': [
  { com: ['amiodarona','dronedarona','levofloxacina','moxifloxacino','haloperidol','quetiapina','risperidona'], nivel: 'alto', titulo: 'Sotalol + Medicamento que Prolonga QT', efeito: 'Sotalol prolonga o intervalo QT — combinação com outros fármacos que também prolongam o QT multiplica o risco de arritmia grave (torsades de pointes) e parada cardíaca.', conduta: '❌ Contraindicado com outros fármacos que prolongam o QT. Sempre verificar com cardiologista antes de iniciar qualquer medicamento novo.' },
  { com: ['insulina','glibenclamida','gliclazida','glimepirida','metformina'], nivel: 'moderado', titulo: 'Sotalol + Antidiabético', efeito: 'Sotalol é um betabloqueador — mascara os sintomas clássicos de hipoglicemia (tremor, taquicardia) exceto a sudorese. O paciente pode não perceber a queda de glicose a tempo.', conduta: '⚠️ Monitorar glicemia com mais frequência. Orientar o paciente a atentar à sudorese como sinal de hipoglicemia.' },
  { com: ['ibuprofeno','diclofenaco','naproxeno','aine'], nivel: 'moderado', titulo: 'Sotalol + AINE', efeito: 'AINEs retêm sódio e água — podem reduzir o efeito anti-hipertensivo e antiarrítmico do sotalol. Também aumentam risco de insuficiência renal.', conduta: '⚠️ Evitar AINEs. Usar paracetamol ou dipirona para dor. Monitorar pressão arterial e frequência cardíaca.' },
  { com: ['verapamil','diltiazem'], nivel: 'alto', titulo: 'Sotalol + Verapamil / Diltiazem', efeito: 'Soma de efeitos inotrópicos e cronotrópicos negativos — bradicardia grave, bloqueio cardíaco e insuficiência cardíaca.', conduta: '❌ Evitar a combinação. Se necessário, monitorar ECG e frequência cardíaca rigorosamente.' },
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Sotalol + Álcool', efeito: 'Álcool pode potencializar o efeito hipotensor do sotalol — tontura ao levantar, hipotensão sintomática e risco de quedas.', conduta: '⚠️ Evitar álcool durante o tratamento. Levantar devagar para evitar tontura.' },
  { tipo: 'duplicacao', classe: 'Betabloqueador', nivel: 'alto', titulo: '🔄 Duplicação Terapêutica — Dois Betabloqueadores', efeito: 'Usar sotalol com outro betabloqueador (atenolol, metoprolol, propranolol, carvedilol) soma efeitos depressores cardíacos — bradicardia grave, bloqueio cardíaco e insuficiência cardíaca.', conduta: '❌ Não usar dois betabloqueadores simultaneamente sem prescrição específica e monitorização cardíaca.' }
],

'ticagrelor-60mg-90mg': [
  { com: ['aspirina','ácido acetilsalicílico','aas'], nivel: 'alto', titulo: 'Ticagrelor + Aspirina em Dose Alta (>100mg)', efeito: 'Paradoxalmente, aspirina em doses acima de 100mg/dia REDUZ a eficácia do ticagrelor. Aspirina compete pelo mesmo sítio de ligação na plaqueta — aumenta o risco de trombose.', conduta: '❌ Usar apenas aspirina em dose baixa (75–100mg/dia) junto com ticagrelor. Nunca usar aspirina em dose alta (anti-inflamatória) durante o tratamento.' },
  { com: ['ibuprofeno','diclofenaco','nimesulida','naproxeno','meloxicam'], nivel: 'alto', titulo: 'Ticagrelor + AINE', efeito: 'AINEs têm efeito antiagregante e irritam a mucosa gástrica — combinação com antiagregante plaquetário multiplica o risco de sangramento gastrointestinal grave.', conduta: '❌ Evitar AINEs. Usar paracetamol ou dipirona para dor e febre. Comunicar ao médico qualquer necessidade de anti-inflamatório.' },
  { com: ['fluoxetina','sertralina','paroxetina','escitalopram','venlafaxina'], nivel: 'moderado', titulo: 'Ticagrelor + ISRS', efeito: 'ISRS reduzem a serotonina plaquetária — efeito antiagregante adicional que potencializa o risco de sangramento em combinação com ticagrelor.', conduta: '⚠️ Usar protetor gástrico (IBP). Monitorar sinais de sangramento (fezes escuras, tontura). Comunicar ao médico.' },
  { com: ['ketoconazol','itraconazol','claritromicina','ritonavir'], nivel: 'alto', titulo: 'Ticagrelor + Inibidor Forte do CYP3A4', efeito: 'Ticagrelor é metabolizado pelo CYP3A4 — inibidores fortes elevam muito seus níveis séricos, potencializando o efeito antiagregante e o risco de sangramento grave.', conduta: '❌ Contraindicado. Buscar antibiótico ou antifúngico alternativo.' },
  { com: ['rifampicina','carbamazepina','fenitoína','fenobarbital'], nivel: 'alto', titulo: 'Ticagrelor + Indutor do CYP3A4', efeito: 'Indutores do CYP3A4 reduzem drasticamente os níveis de ticagrelor — perda do efeito antiagregante com risco de trombose e infarto.', conduta: '❌ Contraindicado. Buscar alternativa ao indutor. Discutir com cardiologista.' },
  { com: ['digoxina'], nivel: 'moderado', titulo: 'Ticagrelor + Digoxina', efeito: 'Ticagrelor inibe o transportador P-gp — pode elevar os níveis de digoxina com risco de toxicidade digitálica (náusea, bradicardia, arritmia).', conduta: '⚠️ Monitorar nível sérico de digoxina ao iniciar ticagrelor.' },
  { com: ['warfarina','varfarina','rivaroxabana','apixabana','dabigatrana'], nivel: 'alto', titulo: 'Ticagrelor + Anticoagulante', efeito: 'Combinação de antiagregante + anticoagulante (terapia dupla/tripla) multiplica muito o risco de sangramento grave — hemorragia digestiva e intracraniana.', conduta: '❌ Usar somente com indicação médica específica e acompanhamento rigoroso. Protetor gástrico é obrigatório.' }
],

'prasugrel-5mg-10mg': [
  { com: ['ibuprofeno','diclofenaco','nimesulida','naproxeno','meloxicam','aine'], nivel: 'alto', titulo: 'Prasugrel + AINE', efeito: 'AINEs têm efeito antiagregante plaquetário e irritam a mucosa gástrica — combinação com prasugrel multiplica o risco de sangramento gastrointestinal grave.', conduta: '❌ Evitar AINEs. Usar paracetamol ou dipirona para dor e febre. Comunicar ao médico qualquer necessidade de anti-inflamatório.' },
  { com: ['warfarina','varfarina','rivaroxabana','apixabana','dabigatrana','acenocumarol'], nivel: 'alto', titulo: 'Prasugrel + Anticoagulante', efeito: 'Terapia combinada de antiagregante + anticoagulante multiplica muito o risco de sangramento grave — hemorragia digestiva e intracraniana.', conduta: '❌ Usar somente com indicação médica específica e acompanhamento rigoroso. Protetor gástrico obrigatório.' },
  { com: ['fluoxetina','sertralina','paroxetina','escitalopram','venlafaxina'], nivel: 'moderado', titulo: 'Prasugrel + ISRS', efeito: 'ISRS têm efeito antiagregante adicional por reduzirem a serotonina plaquetária — potencializa o risco de sangramento em combinação com prasugrel.', conduta: '⚠️ Usar protetor gástrico (IBP). Monitorar sinais de sangramento (fezes escuras, tontura).' },
  { com: ['tramadol','morfina','fentanila','codeína'], nivel: 'moderado', titulo: 'Prasugrel + Opioide', efeito: 'Opioides retardam o esvaziamento gástrico — reduzem e atrasam a absorção de prasugrel, podendo comprometer o efeito antiagregante nas primeiras horas (crítico em síndrome coronariana aguda).', conduta: '⚠️ Comunicar ao médico o uso de opioide. Pode ser necessário ajuste da forma ou via de administração do antiagregante.' },
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Prasugrel + Álcool', efeito: 'Álcool tem efeito antiagregante leve e irrita a mucosa gástrica — combinação com prasugrel aumenta o risco de sangramento gastrointestinal.', conduta: '⚠️ Evitar álcool durante o tratamento. Risco de sangramento gastrointestinal aumentado.' }
],

'talidomida-50mg-100mg': [
  { com: ['dexametasona','prednisona','prednisolona','corticoide'], nivel: 'alto', titulo: 'Talidomida + Corticoide (Especialmente Dexametasona)', efeito: 'Combinação amplamente usada em mieloma múltiplo, mas eleva muito o risco de tromboembolismo venoso (TVP e embolia pulmonar) — pode ser fatal.', conduta: '❌ O médico deve prescrever profilaxia antitrombótica obrigatória (heparina ou aspirina de acordo com o risco). Nunca interromper sem orientação.' },
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Talidomida + Álcool', efeito: 'Álcool potencializa a sedação da talidomida e pode piorar a neuropatia periférica (formigamento, dor nos pés e mãos) — efeito adverso já frequente da talidomida.', conduta: '⚠️ Evitar álcool durante o tratamento. Talidomida causa sonolência intensa — álcool agrava ainda mais.' },
  { com: ['diazepam','clonazepam','alprazolam','lorazepam','zolpidem','zopiclona'], nivel: 'alto', titulo: 'Talidomida + Benzodiazepínico / Hipnótico', efeito: 'Potencialização intensa da sedação do SNC — risco de sedação profunda, confusão mental e depressão respiratória.', conduta: '❌ Evitar. Se necessário, usar a menor dose e monitorar rigorosamente.' },
  { com: ['carbamazepina','fenitoína','rifampicina'], nivel: 'moderado', titulo: 'Talidomida + Indutor Enzimático', efeito: 'Indutores do CYP3A4 podem reduzir os níveis séricos da talidomida, comprometendo a eficácia do tratamento.', conduta: '⚠️ Monitorar resposta ao tratamento. Comunicar ao médico o uso de anticonvulsivantes ou rifampicina.' },
  { com: ['etinilestradiol','anticoncepcional','contraceptivo'], nivel: 'alto', titulo: 'Talidomida + Contracepção (OBRIGATÓRIA)', efeito: 'Talidomida causa malformações fetais gravíssimas (focomelia) — qualquer exposição durante a gravidez é catastrófica. NÃO é uma interação adversa, mas uma obrigação do tratamento.', conduta: '❌ Mulheres em idade fértil DEVEM usar dois métodos contraceptivos simultâneos durante o tratamento e por 1 mês após. O não cumprimento implica risco grave ao feto.' },
  { com: ['cisplatina','quimioterapia'], nivel: 'moderado', titulo: 'Talidomida + Quimioterapia Neurotóxica', efeito: 'Talidomida já causa neuropatia periférica — combinação com quimioterápicos neurotóxicos (cisplatina, vincristina) soma e agrava o dano nervoso.', conduta: '⚠️ Monitorar neuropatia (formigamento, dor, fraqueza nas mãos e pés). Comunicar imediatamente ao oncologista qualquer piora.' }
],

'isotretinoina-10mg-20mg': [
  { com: ['vitamina a','vitamina-a','retinol','suplemento de vitamina a'], nivel: 'alto', titulo: 'Isotretinoína + Vitamina A', efeito: 'Isotretinoína é um derivado da vitamina A — suplementação adicional de vitamina A causa hipervitaminose A grave: dor de cabeça intensa, náusea, visão turva e toxicidade hepática.', conduta: '❌ Contraindicado. Não usar suplementos de vitamina A ou multivitamínicos com doses elevadas de vitamina A durante o tratamento.' },
  { com: ['doxiciclina','minociclina','tetraciclina'], nivel: 'alto', titulo: 'Isotretinoína + Tetraciclina / Minociclina', efeito: 'Combinação aumenta muito o risco de hipertensão intracraniana benigna (pseudotumor cerebri) — dor de cabeça intensa, visão turva, náusea e vômito. Pode causar dano permanente à visão.', conduta: '❌ Contraindicado. Nunca combinar isotretinoína com antibióticos do grupo das tetraciclinas.' },
  { com: ['etinilestradiol','anticoncepcional','contraceptivo'], nivel: 'alto', titulo: 'Isotretinoína + Contracepção (OBRIGATÓRIA)', efeito: 'Isotretinoína é altamente teratogênica — causa malformações fetais graves. NÃO é interação adversa, mas obrigação do tratamento (programa de prevenção de gravidez).', conduta: '❌ Mulheres em idade fértil DEVEM usar dois métodos contraceptivos simultâneos, iniciados 1 mês antes do tratamento e mantidos 1 mês após. Exame de gravidez mensal obrigatório.' },
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Isotretinoína + Álcool', efeito: 'Álcool potencializa a toxicidade hepática da isotretinoína — risco de elevação de enzimas hepáticas e dano ao fígado. Também eleva os triglicerídeos, efeito adverso já frequente da isotretinoína.', conduta: '⚠️ Evitar álcool durante todo o tratamento. Exames de função hepática e triglicerídeos são monitorados regularmente.' },
  { com: ['metotrexato'], nivel: 'alto', titulo: 'Isotretinoína + Metotrexato', efeito: 'Combinação potencializa a hepatotoxicidade — risco elevado de dano hepático grave.', conduta: '❌ Contraindicado. Nunca usar as duas substâncias simultaneamente.' },
  { com: ['carbamazepina'], nivel: 'moderado', titulo: 'Isotretinoína + Carbamazepina', efeito: 'Isotretinoína pode reduzir os níveis séricos de carbamazepina — risco de piora do controle das crises epilépticas.', conduta: '⚠️ Monitorar nível sérico de carbamazepina e controle das crises ao iniciar isotretinoína.' }
],

'acarbose': [
  { com: ['insulina','insulina nph','insulina regular','insulina glargina'], nivel: 'moderado', titulo: 'Acarbose + Insulina', efeito: 'Acarbose retarda a absorção de carboidratos — combinação com insulina pode causar hipoglicemia. Importante: em caso de hipoglicemia com acarbose, a glicose simples (sacarose) é absorvida mais lentamente, portanto a correção deve ser feita com GLUCOSE PURA.', conduta: '⚠️ Monitorar glicemia com frequência. Em hipoglicemia, usar glucose pura (dextrose), não açúcar de mesa. Comunicar ao médico.' },
  { com: ['glibenclamida','gliclazida','glimepirida','glipizida'], nivel: 'moderado', titulo: 'Acarbose + Sulfonilureia', efeito: 'Combinação pode causar hipoglicemia. Na correção da hipoglicemia com acarbose, o açúcar de mesa (sacarose) não funciona rapidamente — a sacarose é um dissacarídeo que a acarbose bloqueia.', conduta: '⚠️ Em caso de hipoglicemia, corrigir com glucose pura ou mel. Monitorar glicemia regularmente. Comunicar ao médico.' },
  { com: ['amilase','pancreatina','enzima digestiva'], nivel: 'moderado', titulo: 'Acarbose + Enzimas Digestivas (Amilase)', efeito: 'Enzimas digestivas contendo amilase degradam a acarbose no intestino — reduzem seu efeito no controle glicêmico pós-prandial.', conduta: '⚠️ Evitar enzimas digestivas com amilase durante o uso de acarbose. Comunicar ao médico o uso de qualquer suplemento digestivo.' },
  { com: ['álcool','alcool'], nivel: 'moderado', titulo: 'Acarbose + Álcool', efeito: 'Álcool pode causar hipoglicemia ao ser usado com antidiabéticos. Com acarbose, a correção da hipoglicemia com açúcar comum é mais lenta — risco de hipoglicemia prolongada.', conduta: '⚠️ Evitar álcool em jejum. Monitorar glicemia. Em hipoglicemia, usar glucose pura.' },
  { com: ['colestiramina'], nivel: 'baixo', titulo: 'Acarbose + Colestiramina', efeito: 'Colestiramina pode potencializar o efeito hipoglicemiante da acarbose ao retardar a absorção intestinal de glicose.', conduta: '✅ Monitorar glicemia. Pode ser necessário ajuste de dose sob orientação médica.' }
],

'gliclazida': [
  { com: ['álcool','alcool'], nivel: 'alto', titulo: 'Gliclazida + Álcool', efeito: 'Álcool potencializa o efeito hipoglicemiante da gliclazida — risco de hipoglicemia grave e prolongada. Além disso, álcool pode causar reação tipo dissulfiram com sulfonilureias (rubor, calor, náusea).', conduta: '❌ Evitar álcool durante o tratamento, especialmente em jejum. Hipoglicemia com álcool pode ser grave e prolongada.' },
  { com: ['insulina'], nivel: 'moderado', titulo: 'Gliclazida + Insulina', efeito: 'Combinação potente de hipoglicemiantes — risco elevado de hipoglicemia grave, especialmente com exercício, jejum ou dose errada.', conduta: '⚠️ Monitorar glicemia rigorosamente. Combinação usada em alguns casos, mas exige ajuste cuidadoso pelo médico.' },
  { com: ['fluconazol','miconazol'], nivel: 'alto', titulo: 'Gliclazida + Antifúngico Azólico', efeito: 'Fluconazol e miconazol inibem CYP2C9 — bloqueiam o metabolismo da gliclazida, elevando muito seus níveis séricos e causando hipoglicemia grave e prolongada.', conduta: '❌ Monitorar glicemia com muita frequência. Pode ser necessário reduzir a dose de gliclazida. Comunicar ao médico.' },
  { com: ['betabloqueador','atenolol','propranolol','metoprolol','bisoprolol','carvedilol'], nivel: 'moderado', titulo: 'Gliclazida + Betabloqueador', efeito: 'Betabloqueadores mascaram os sintomas de hipoglicemia mediados pelo sistema nervoso simpático (tremor, taquicardia, ansiedade) — o paciente pode não perceber a queda do açúcar a tempo. A sudorese é preservada.', conduta: '⚠️ Monitorar glicemia com mais frequência. Orientar o paciente a atentar à sudorese como sinal de hipoglicemia.' },
  { com: ['rifampicina'], nivel: 'moderado', titulo: 'Gliclazida + Rifampicina', efeito: 'Rifampicina induz CYP2C9 — acelera o metabolismo da gliclazida, reduzindo muito seus níveis séricos e comprometendo o controle glicêmico.', conduta: '⚠️ Monitorar glicemia ao iniciar rifampicina. Pode ser necessário aumentar a dose de gliclazida sob orientação médica.' },
  { com: ['ibuprofeno','diclofenaco','naproxeno','aine'], nivel: 'moderado', titulo: 'Gliclazida + AINE', efeito: 'AINEs podem potencializar o efeito hipoglicemiante das sulfonilureias por deslocamento proteico e inibição renal — risco de hipoglicemia.', conduta: '⚠️ Monitorar glicemia ao usar AINEs. Preferir paracetamol ou dipirona para dor.' },
  { com: ['ciprofloxacino','levofloxacino','moxifloxacino'], nivel: 'moderado', titulo: 'Gliclazida + Fluoroquinolona', efeito: 'Fluoroquinolonas podem causar tanto hipoglicemia quanto hiperglicemia em pacientes usando sulfonilureias — desregulação glicêmica imprevisível.', conduta: '⚠️ Monitorar glicemia com mais frequência durante o antibiótico. Comunicar ao médico qualquer alteração.' },
  { tipo: 'duplicacao', classe: 'Sulfonilureia', nivel: 'alto', titulo: '🔄 Duplicação Terapêutica — Duas Sulfonilureias', efeito: 'Usar gliclazida junto com outra sulfonilureia (glibenclamida, glimepirida) soma o efeito hipoglicemiante de forma perigosa — risco de hipoglicemia grave.', conduta: '❌ Nunca usar duas sulfonilureias simultaneamente. Comunicar ao médico se outro antidiabético foi prescrito.' }
],

'glimepirida': [
  { com: ['álcool','alcool'], nivel: 'alto', titulo: 'Glimepirida + Álcool', efeito: 'Álcool potencializa o efeito hipoglicemiante da glimepirida — risco de hipoglicemia grave e prolongada. Pode causar reação tipo dissulfiram (rubor, calor, náusea).', conduta: '❌ Evitar álcool durante o tratamento, especialmente em jejum. Hipoglicemia alcoólica pode ser grave e prolongada.' },
  { com: ['insulina'], nivel: 'moderado', titulo: 'Glimepirida + Insulina', efeito: 'Combinação de hipoglicemiantes — risco elevado de hipoglicemia grave, especialmente com exercício, jejum ou dose errada.', conduta: '⚠️ Monitorar glicemia rigorosamente. Combinação exige ajuste cuidadoso pelo médico.' },
  { com: ['fluconazol','miconazol'], nivel: 'alto', titulo: 'Glimepirida + Antifúngico Azólico', efeito: 'Fluconazol e miconazol inibem CYP2C9 — elevam muito os níveis de glimepirida com risco de hipoglicemia grave e prolongada.', conduta: '❌ Monitorar glicemia com muita frequência. Pode ser necessário reduzir a dose de glimepirida. Comunicar ao médico.' },
  { com: ['betabloqueador','atenolol','propranolol','metoprolol','bisoprolol','carvedilol'], nivel: 'moderado', titulo: 'Glimepirida + Betabloqueador', efeito: 'Betabloqueadores mascaram os sintomas simpáticos de hipoglicemia (tremor, taquicardia) — o paciente pode não perceber a queda do açúcar. A sudorese é preservada.', conduta: '⚠️ Monitorar glicemia com mais frequência. Orientar o paciente a atentar à sudorese como sinal de hipoglicemia.' },
  { com: ['rifampicina'], nivel: 'moderado', titulo: 'Glimepirida + Rifampicina', efeito: 'Rifampicina induz CYP2C9 — reduz os níveis de glimepirida e compromete o controle glicêmico.', conduta: '⚠️ Monitorar glicemia. Pode ser necessário aumentar a dose de glimepirida sob orientação médica.' },
  { com: ['ibuprofeno','diclofenaco','naproxeno','aine'], nivel: 'moderado', titulo: 'Glimepirida + AINE', efeito: 'AINEs podem potencializar o efeito hipoglicemiante das sulfonilureias — risco de hipoglicemia.', conduta: '⚠️ Monitorar glicemia ao usar AINEs. Preferir paracetamol ou dipirona para dor.' },
  { com: ['colesevelam'], nivel: 'moderado', titulo: 'Glimepirida + Colesevelam', efeito: 'Colesevelam pode reduzir a absorção de glimepirida no intestino — comprometimento do efeito hipoglicemiante.', conduta: '⚠️ Tomar glimepirida pelo menos 4h antes do colesevelam. Monitorar glicemia.' },
  { tipo: 'duplicacao', classe: 'Sulfonilureia', nivel: 'alto', titulo: '🔄 Duplicação Terapêutica — Duas Sulfonilureias', efeito: 'Usar glimepirida junto com outra sulfonilureia (gliclazida, glibenclamida) soma efeitos hipoglicemiantes de forma perigosa.', conduta: '❌ Nunca usar duas sulfonilureias simultaneamente. Comunicar ao médico se outro antidiabético foi prescrito.' }
]

};

let updated = 0, notFound = 0;
for (const [slug, interacoes] of Object.entries(INTERACOES)) {
  const idx = data.findIndex(m => m.slug === slug);
  if (idx === -1) { console.error('NÃO ENCONTRADO:', slug); notFound++; continue; }
  data[idx].interacoes = interacoes;
  updated++;
  console.log('OK:', data[idx].nome, '—', interacoes.length, 'interações');
}

fs.writeFileSync('./src/data/medicamento.json', JSON.stringify(data, null, 2), 'utf8');
console.log('\nTotal atualizado:', updated, '| Não encontrado:', notFound);
