[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*.cjs"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/lote*.json"
  [headers.values]
    X-Robots-Tag = "noindex"
